# Generated by Django 5.1.1 on 2024-12-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tg_chat_id_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ID телеграм-чата'),
        ),
    ]
