# Generated by Django 5.1.1 on 2024-12-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tg_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tg_chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
