# Generated by Django 5.1.1 on 2024-12-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_users',
        ),
    ]
